// src/generators/component/templates/react/component-with-d3.tsx
import { select<% if (isTS) { %>, Selection<% } %> } from 'd3-selection';
import React, { useEffect, useRef } from 'react';
import styles from './styles.scss';
<% if (isTS) { %>
interface <%= className %>Props {
  color?: string; 
}
<% } %>
const <%= className %><% if (isTS) { %>: React.FC<<%= className %>Props><% } %> = ({ color = 'black' }) => {
  const root = useRef<% if (isTS) { %><HTMLDivElement | null><% } %>(null);
  const svg = useRef<% if (isTS) { %><Selection<SVGSVGElement, unknown, null, undefined> | null><% } %>(null);
  const g = useRef<% if (isTS) { %><Selection<SVGGElement, unknown, null, undefined> | null><% } %>(null);
  const rect = useRef<% if (isTS) { %><Selection<SVGRectElement, unknown, null, undefined> | null><% } %>(null);
  
  useEffect(() => {
    svg.current = select(root.current)
      .append('svg')
      .attr('width', 400)
      .attr('height', 300);

    g.current = svg.current.append('g');

    rect.current = g.current
      .append('rect')
      .attr('x', 0)
      .attr('y', 0)
      .attr('rx', 3)
      .attr('ry', 3)
      .attr('width', '100%')
      .attr('height', '100%');
  }, []);

  useEffect(() => {
    if (!g.current) {
      return;
    }

    g.current.attr('fill', color);
  }, [color]);

  return <div ref={root} className={styles.root}></div>;
};

export default <%= className %>;

// src/generators/component/templates/svelte/component-with-d3.svelte
<script<% if (isTS) { %> lang="ts"<% } %>>
  export let color<% if (isTS) { %>: string<% } %> = 'black';

  import { select } from 'd3-selection';<% if (isTS) { %>
  import type { Selection } from 'd3-selection';<% } %>
  import { afterUpdate, onMount } from 'svelte';

  let root<% if (isTS) { %>: HTMLDivElement<% } %>;
  let svg<% if (isTS) { %>: Selection<SVGSVGElement, unknown, null, undefined><% } %>;
  let g<% if (isTS) { %>: Selection<SVGGElement, unknown, null, undefined><% } %>;
  let rect<% if (isTS) { %>: Selection<SVGRectElement, unknown, null, undefined><% } %>;

  onMount(() => {
    svg = select(root)
      .append('svg')
      .attr('width', 400)
      .attr('height', 300);

    g = svg.append('g').attr('fill', color);

    rect = g
      .append('rect')
      .attr('x', 0)
      .attr('y', 0)
      .attr('rx', 3)
      .attr('ry', 3)
      .attr('width', '100%')
      .attr('height', '100%');
  });

  afterUpdate(() => {
    g.attr('fill', color);
  });
</script>

<style lang="scss">
  div {
    border: 1px solid rgb(255, 115, 0);
    padding: 20px;
    text-align: center;
    color: black;
  }
</style>

<div bind:this={root} />
